ScriptoNaughts/Scriptomatics

controllers/api/index.js, controllers/api/message-routes.js, controllers/api/script-routes.js, controllers/api/user-routes.js, controllers/home-routes.js, controllers/index.js
Created the index files that set up the middleware which defines the prefix to the path of the route for operations related to the user, scripts, and messages.
=> chore: Set up controllers file structure and set up routes for the home page and api routes (user, scripts, messages resources)

server.js
- The server setup adds a middleware to the controllers folder for the routes within our application
- The server setup adds a middleware with a session configuration and Sequelize store setup.
- The session configuration includes cookie settings, resave, and saveUninitialized options. 
- The Sequelize store connects the session to the Sequelize database.
=> Create server setup with middleware for routes, session configuration and sequelize store to database

controllers/api/user-routes.js
- Added a GET route to retrieve a single user by their id
- Added a POST route to create a new user with required fields (first name, last name, email, password, and role title)
- The POST route uses a role title to retrieve the corresponding role id from the database
- The password encryption is handled by hooks in the sequelize model
- Added error handling for email and password validation errors
- Added a DELETE route to delete a user by their id
=> Add user controller routes for GET, POST, and DELETE requests

controllers/api/user-routes.js, models/TBLUser.js
- Created an async function checkPassword which is an instance method in the TBLUser model. checkPassword compares a user-provided password with the encrypted password that is stored in the database
- Add a POST route for /login to authenticate user login information
- In the login route, we search the database for the user with the provided email, then use the checkPassword function to verify the user-provided password
- If the password is valid, set up a session for the authenticated user with a loggedIn variable
- Add a POST route for /logout to destroy the session associated with the client making the request
- If the client's session is destroyed, return a 204 status code (204 since no content is being returned), otherwise, return 404
=> Added login and logout functionality to the user routes

public/css/style.css, public/templates/agent-home.html
added hamburger menu for better responsiveness
=> adjusted navbar

public/css/style.css, public/templates/agent-browse.html, public/templates/writer-home.html
Created html agent browse page and added minor adjustments to other html templates
=> created html template for agent browse page

controllers/api/message-routes.js, controllers/api/script-routes.js, controllers/home-routes.js
- Changing from ASC to DESC will allows us to return the most recent messages
=> changed the order of the data returned in the GET chat history request from ASC to DESC

public/css/style.css, public/templates/agent-browse.html, public/templates/agent-purchased.html, public/templates/writer-posted.html
adjusted the size of the side menu on all pages and added css styling for better responsiveness
=> minor html adjustments

controllers/api/script-routes.js, controllers/api/user-routes.js, models/index.js
- The script model has 2 foreign keys in the user model, so we need to add aliases to differentiate which foreign key we want to include in the controller route
- Added aliases that allow us to show the authors and agents associated with each script
- Added aliases that allow us to show all the scripts associated with an author or agent
- Added get routes for the script routes to quickly visualize changes made to the script data in the database when using Postman or Insomnia
=> Added aliases for relationships in models table and included them in the controller routes when including models of foreign keys

controllers/api/script-routes.js
- The GET route allows clients to search for scripts written by any author whose name (first or last or combination) is included in the client's search term.
- The route retrieves the client's search term from the URL parameter and removes any whitespace
- We then find all users with a "writer" role and loop through them
- For each user with a "writer" role, we combine their first and last names into one string by removing any whitespace. If the client's search term is included in the combined first and last name of the author's record, it finds all of the author's scripts and adds them to an array.
=> Added GET route to allow client's to search for scripts by an authors name (or part of it)

public/css/style.css, public/templates/agent-browse.html, public/templates/agent-purchased.html, public/templates/homepage.html, public/templates/writer-posted.html, public/templates/writer-workspace.html
Adjusted styling in some of the html templates and style.css
=> styling adjustments

controllers/api/user-routes.js
- In the sign-up route, redirect the user to the homepage after the session is saved
- In the login route, redirect the user to the homepage after the session is saved 
- In the logout route, redirect the user to the main page (with the sign-up and login forms) after the session is destroyed
=> Add redirect functionality to redirect the user's webpage for the signup, login, and logout routes

controllers/api/user-routes.js, controllers/dev/index.js, controllers/dev/user-routes.js, controllers/index.js
- Moved the user routes from the /api folder to the new /dev folder to separate them into client routes and developer routes
- Set up the middleware to give the "/dev" prefix for the developer routes to distinguish them from the client routes
- This will make it easier for developers to access and visualize data from the user routes without interfering with the client-facing application
=> Separated routes into client and developer routes

controllers/home-routes.js
- Added GET request to render the main page with login/signup form
- Added GET request to render the homepage for writers or agents once they are logged in
- Added GET request to render scripts page where writers can view their posted scripts
- Added GET request to render scripts page where agents can view their purchased scripts
- Added GET request to render browse page where agents can browse published scripts
- Added GET request to render workspace where authors can work on their scripts
- Added GET request to render messages page where authors and agents can view users who they have interacted with via messages
=> Added initial setup of routes to render the handlebar pages

controllers/home-routes.js
- Added a GET route to render the homepage for the requesting user based on their roleTitle
- Excluded the user's password from the userData to prevent sensitive information from being returned
- Added a check to ensure userData is not null before rendering the homepage
=> Added GET route to render the homepage. The user data returned can be accessed to render the appropriate homepage given the returned user's roleTitle

controllers/home-routes.js
- Added a GET route to render the scripts page where the requesting writer (user) can view all their published and purchased scripts
- The scripts data that is returned also includes information on the agent (user) that purchased their scripts, but excludes the agent's password as that is sensitive information
- Added a check to ensure scriptData is not null before rendering the scripts page
=> Added GET route to render the requesting writer's published and purchased scripts

controllers/home-routes.js
- Added a GET route to render the scripts page where the requesting agent (user) can view all their purchased scripts
- The scripts data that is returned also includes information on the writer (user) that published the scripts that the agent purchased, but excludes the writer's password as that is sensitive information
- Added a check to ensure scriptData is not null before rendering the scripts page
=> Added GET route to render the requesting agent's purchased scripts

controllers/home-routes.js
- Added a GET route to render the browse page where agents (users) can view all published scripts available on the marketplace
- The scripts data that is returned also includes information on the writer (user) that authored the scripts but excludes the writer's password as that is sensitive information
- Added a check to ensure scriptData is not null before rendering the scripts page
=> Added GET route to show all published scripts to agents on their browse page

controllers/api/user-routes.js, controllers/home-routes.js
- Changed const variable to `let` since it's value is being changed
- Changed name of route extension to reflect the naming convention in the handlebars
- Removed the res.json that appears after res.redirect since you can only have one of them or else you get response headers error
=> minor fixes to routes

controllers/api/user-routes.js, controllers/home-routes.js, models/TBLUser.js, server.js, utils/helpers.js, views/homepage.handlebars, views/layouts/main.handlebars, views/loggedin.handlebars
- Changed the rendered page from "homepage" to "loggedin" since that is the name of the handlebar
- added helper `eq` in the utils folder to allow handlebar if statements to compare the values of 2 variables
- connected the helpers file to the handlebars engine instance
- applied the `eq` helper in the handlebars to check the userID stores in the session
=> Connected the user routes and home routes to the handlebars

controllers/api/user-routes.js, controllers/home-routes.js, server.js
- Fixed user-routes /login and /logout routes to properly store the users ID in the session
- Changed the session cookie configuration's "secure" property to false. This will allow sessions to be stored over HTTP protocols
=> Fixed session storage bug

public/templates/agent-purchased.html, views/loggedin.handlebars, views/partials/agent-purchased.handlebars, views/partials/scripts-card.handlebars, views/partials/writer-posted.handlebars, views/partials/writer-workspace.handlebars
- added handlebars for writer and agent posted and purchased scripts
- edited buttons in workspace
=> Luba feature handlebars

controllers/api/script-routes.js, controllers/home-routes.js, public/css/style.css, public/js/agent-browse.js, utils/helpers.js, views/agent-browse.handlebars, views/partials/agent-browse.handlebars, views/partials/agent-purchased.handlebars, views/partials/writer-posted.handlebars
- Added buttons below the script previews that allow the agent to message the writer or purchase a script
- The purchase script triggers a click event listener that allows a script to be purchased by the requesting user
- The text of the purchase button changes as well as its color, to alert the user that their purchase has been successful 
- The newly purchased scripts will be removed from the browse page when it is reloaded
-  The newly purchased scripts will be moved to the "purchased scripts" tab
=> Completed agent browse page
